#!/bin/sh

if [ -z $AQCC_DETAIL ]
then
    AQCC_DETAIL=./aqcc_detail
fi

function print_usage_to_fail() {
    echo "Usage: aqcc [-c, -S] input-files... -o output-file"
    echo
    exit 1
}

outft='e'
outfile='a.out'
infiles=()
while (( $# > 0 ))
do
    case "$1" in
        '-o')
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                print_usage_to_fail
            fi
            outfile=$2
            shift 2
            ;;
        '-c')
            outft='o'
            shift
            ;;
        '-S')
            outft='s'
            shift
            ;;
        *)
            infiles+=("$1")
            shift
            ;;
    esac
done

case $outft in
    s)
        [ ${#infiles[@]} -eq 1 ] || print_usage_to_fail
        $AQCC_DETAIL cs "${infiles[0]}" "$outfile"
        ;;

    o)
        echo "o"
        [ ${#infiles[@]} -eq 1 ] || print_usage_to_fail
        case "${infiles[0]}" in
            *c)
                sfile=$(mktemp)
                $AQCC_DETAIL cs "${infiles[0]}" $sfile
                $AQCC_DETAIL so $sfile "$outfile"
                rm $sfile
                ;;
            *s)
                $AQCC_DETAIL so "${infiles[0]}" "$outfile"
                ;;
            *)
                print_usage_to_fail
                ;;
        esac
        ;;

    e)
        insrc=()
        tempfiles=()

        for ((i = 0; i < ${#infiles[@]}; i++))
        do
            fname="${infiles[$i]}"
            case $fname in
                *c)
                    sfile=$(mktemp)
                    ofile=$(mktemp)
                    $AQCC_DETAIL cs "$fname" $sfile
                    $AQCC_DETAIL so $sfile $ofile
                    insrc+=($ofile)
                    rm $sfile
                    tempfiles+=($ofile)
                    ;;

                *s)
                    ofile=$(mktemp)
                    $AQCC_DETAIL so "$fname" $ofile
                    insrc+=($ofile)
                    tempfiles+=($ofile)
                    ;;

                *o)
                    insrc+=("$fname")
                    ;;
            esac
        done

        $AQCC_DETAIL oe "${insrc[@]}" "$outfile"
        chmod +x "$outfile"

        for ((i = 0; i < ${#tempfiles[@]}; i++))
        do
            rm "${tempfiles[$i]}"
        done
        ;;
esac
