#!/bin/bash

if [ -z $AQCC_DETAIL ]
then
    # Use aqcc_detail located in the directory including this script.
    AQCC_DETAIL=`dirname ${0}`/aqcc_detail
fi

function print_usage_to_fail() {
    echo "Usage: aqcc [-c, -S] input-files... -o output-file"
    echo
    exit 1
}

outft='e'
outfile='a.out'
infiles=()
verbose=0
while (( $# > 0 ))
do
    case "$1" in
        '-o')
            if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                print_usage_to_fail
            fi
            outfile=$2
            shift 2
            ;;
        '-c')
            outft='o'
            shift
            ;;
        '-S')
            outft='s'
            shift
            ;;
        '-v')
            verbose=1
            shift
            ;;
        *)
            infiles+=("$1")
            shift
            ;;
    esac
done

function exec_aqcc_detail() {
    [ $verbose = 1 ] && echo $AQCC_DETAIL "$@"
    $AQCC_DETAIL "$@"
}

case $outft in
    s)
        [ ${#infiles[@]} -eq 1 ] || print_usage_to_fail
        exec_aqcc_detail cs "${infiles[0]}" "$outfile"
        ;;

    o)
        [ ${#infiles[@]} -eq 1 ] || print_usage_to_fail
        case "${infiles[0]}" in
            *c)
                sfile=$(mktemp)
                exec_aqcc_detail cs "${infiles[0]}" $sfile
                exec_aqcc_detail so $sfile "$outfile"
                rm $sfile
                ;;
            *s)
                exec_aqcc_detail so "${infiles[0]}" "$outfile"
                ;;
            *)
                print_usage_to_fail
                ;;
        esac
        ;;

    e)
        insrc=()
        tempfiles=()

        for ((i = 0; i < ${#infiles[@]}; i++))
        do
            fname="${infiles[$i]}"
            case $fname in
                *c)
                    sfile=$(mktemp)
                    ofile=$(mktemp)
                    exec_aqcc_detail cs "$fname" $sfile
                    exec_aqcc_detail so $sfile $ofile
                    insrc+=($ofile)
                    rm $sfile
                    tempfiles+=($ofile)
                    ;;

                *s)
                    ofile=$(mktemp)
                    exec_aqcc_detail so "$fname" $ofile
                    insrc+=($ofile)
                    tempfiles+=($ofile)
                    ;;

                *o)
                    insrc+=("$fname")
                    ;;
            esac
        done

        exec_aqcc_detail oe "${insrc[@]}" "$outfile"
        chmod +x "$outfile"

        for ((i = 0; i < ${#tempfiles[@]}; i++))
        do
            rm "${tempfiles[$i]}"
        done
        ;;
esac
